### ISSUE TITLE
Is it possible to run plugin to index queries without gatsby build?

### ISSUE THREAD

**Issue by marceleq27** [algolia/gatsby-plugin-algolia#75] opened 2020-05-28 12:40 UTC
As in title, I mean I want to index query in development mode to check if it's working properly. Now I must run `gatsby build`. Is there a way to omit that?

**Comment by Haroenv** [comment] 2020-06-01 07:47
What's the reason you can't run `Gatsby build` on development? Since we are listening to the `onPostBuild` event from Gatsby, I think if you make a custom Gatsby plugin you might be able to trigger that manually, however I'm not sure how that would be done since I haven't tried it myself. Worth asking on the Gatsby repo IMO.

**Comment by marceleq27** [comment] 2020-06-01 11:26
It's no problem to run `gatsby build` but im in quite big project and every build takes a few minutes and it's really hard to test it again and again. Maybe good idea is to add something like devMode which index to algolia on development? Idk, but anyway thanks for help 🙂

**Comment by Haroenv** [comment] 2020-06-01 11:39
The problem is that some of the other plugins you can use also use the onPostBuild hook, and could add things to the graphql schema you want to query

**Comment by marceleq27** [comment] 2020-06-01 11:46
Maybe I'll try to fork repo in next few days, and see if there is a solution for this problem 😛

**Comment by Haroenv** [comment] 2021-07-30 08:02
Feel free still to open a PR if this is behaviour you want, but for the time being I'll close the issue :)

**Closed by Haroenv** 2021-07-30 08:02 UTC
